language: python
python:
  - '3.9.0'
sudo: true

branches:
  only:
    - main

install:
  - sudo apt-get update
  - sudo apt install clang
  - sudo add-apt-repository ppa:cs50/ppa -y
  - sudo apt-get install astyle
  - make deps

script:
  - make all
